apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aardvark-prod
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: aardvark-prod
  source:
    repoURL: https://github.com/pkredhat/aardvark-gitops
    targetRevision: master
    path: .
    helm:
      valueFiles:
        - helm/app/values.yaml
        - envs/prod/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
