apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aardvark-dev
  namespace: openshift-gitops
  labels:
    rht-gitops.com/janus-argocd: aardvark-apps
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: aardvark-dev
  source:
    repoURL: https://github.com/pkredhat/aardvark-gitops
    targetRevision: master
    path: .
    helm:
      valueFiles:
        - helm/app/values.yaml
        - envs/dev/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true




