app:
  name: aardvark
image:
  repository: quay.io/your-org/aardvark
  tag: "1.0.0"
  pullPolicy: IfNotPresent
replicaCount: 1
service:
  type: ClusterIP
  port: 80
route:
  enabled: true
  host: ""
resources: {}
