app:
  name: aardvark
image:
  repository: https://quay-67h8m.apps.cluster-67h8m.67h8m.sandbox698.opentlc.com/pkredhat/aardvark
  tag: "latest"
  pullPolicy: IfNotPresent
replicaCount: 1
service:
  type: ClusterIP
  port: 80
route:
  enabled: true
  host: ""
resources: {}
