replicaCount: 2
image:
  tag: "stage"
route:
  host: "qa"
postgres:
  enabled: true
  image: registry.redhat.io/rhel9/postgresql-16:1-71
  port: 5432
  storage:
    enabled: false
    size: 1Gi
  auth:
    user: postgres
    password: postgres
    database: inventory
